language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: BfRADL9ViOOyIJJd5TYo+SqvVvIPFfOlCgkXlzDsqvZNtLna+PrBaHOyL6w9xSQHDU/2olme2/gGX35OdPtRQhdXcDrJ7tfhwNGYR58d32bTdqZKf5eIQ/RfRDveMq2FQDGDoKBrN8rCeeg74uQ4jBLrz58KhTI9NEJqNLLrTo4ig2c7sMCUSIxThPMzkYPYa0WuZCMr3kJl9a/RCSBo6Q21gYWljYIdTsEKrBpeom1IZffM8USeCDvm7kSC0mo0No8F6Fet7ZVlq/FpeGmd/8k9dbIpImF2a/e1jrksmHOu04oPns0rxJ6sGVT87NWELW2LmFjAJ6zJCa2QcPygKh3jI+Ek4Gb9lRbHKV+cmLKRKfV8qu61Y3eIUv74lJnNH12GmAzT3b1mrWuPqECxGeJtQ3RKsjUpXpJPNOZuT16uBH1Mk7bWpMGFo6j8nkaz+ixyKXvM5SfW/7wyIoPe5CLSSQyPOBHdjf1D+npKykCi4/Qp/iWrgT4X6/qy55xjyF/hBdC9JQGSiLr1/Mp5X8qNi1T54u93X0vYbsv60BUxDt6HDhUxu49fUuRFBu2CITMHaXDc5VQrkvcq91mKp3il1U5wgyJD7nRXWcpn5CmCxzhfe1YXXcYfPZ1IpbuiEOLcoCX9bwvUMqLVhUlPcZFAxTbdOK17A0aCYxSrXCE=
  app: javahelloapp
  on:
    repo: neopragma/javahelloapp
