language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: OC8GMsx3d8wCxNVuP/CDHoF9SOewC5YCqGKUCFMw10/kjC65z6TibSV4P6Pm6pcuBGEu0wsXhu1a5E/rfFg2VBcb8qdrIxnw/nJWR4TNjBtdeu/CdoPCQWboXJauNh2T1FCoBgijroCyDuicNfP3RpuRu57Ega+NJsv4rAtKDTbEvw6d3xePBy6EEsBU40Mq1/yPjyakq1pVnDSqQ7p6rdYY6QwvkJr8A6+VQl4qK54ygAg5YTXxX4OIUAVcg0t+U0u4XILgah5g1+zwreRjNX1MSbP807boURBvHa66WSVdytctXA4NWKkt3wcvxyE+ZEKF0C3ylPp7SSVW3XveW4Y1FqNOzBOatRR+TjT6s4iRRXm+Zn72a8sRCD2/HpuzXrf+VTDiEtUy1xyAFkcUAWI1oWMkaX4kqVWNOKQJfrAOmKj7/uPMkKAAL3Ql6rcLaeepbrlYao19XKbzblp809oFiO40IoHb+UT/RGu20uzwsmvub3377IygEeLltEiu5tBt7Ty6FzegQH1ovXnfQMTO5pUTkZ9/SL8mkUiTtMcTPxIIRFNM6ZxF2Omc+pCNo2iPBmT4hb/3vZdlsY3VkG+RBfFdBiRDopvgaAuHSXkdEQx9YEA1vw1cFyby+bH/6oFQsWGaTSkkxooVhQhMvrZlPnF/398gzKOW9Ddnz7Y=
