language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: L71+71Ory/QyHRcPdcx8gcbwyUWzCM1nHFItw6Wu7NVgU0PsQj96MzkPrSkdw7TEmoqrOgMjdijbkr0NFTP6d6IeyLB93UmwOIdcV+SeMQ+j7mqi3FEOD+saAX9WoupSrVx9gDkvYBSwUql1QLDlyZY3mpFQzZ6/ZJ4RPxGvMtLa4sMWYwCUydH7I1E7Pyd4yDruh/L8Yf5hH4YpSmDWEERSccPtDanAf6Tp0KClVtD+Hrh4D5TZ0gkyH1B+ivKrqxPbQ4JUQaNB8aVECvou4dIs7gN4rF+ie5X4yDKGrbHrO9ieaBPXugnluEKaiknt00dAbHtoDouhp21nnaOp3kucUpkBCFmXfJjvNmTM5jq18trRRs+v/L+7UoEuV7i4OWNBJ4oYs58G3GueGKvogp0yGpnIHEDM0X7M5lJvGlK0kCpVQ0mHZ2kpiuwFP7uyqiF/+G/i9yb38MGGRk4ELlZlST6EZla9ix0w51U38NtqjxWFTdd2ShN6nKXcmEiNH/QT6EzCpbOBVXW018F8UShaiOtwWkhjOAIhU+2kJQagDimDtBq1/hCg6ChwVryUOko8BmNeGTmVGZeIVkdmEU6yRyRoziH3xryXx/fcD+l6kset3vddCW4AvIIcoAa6NluYkyi23tdp8CPVlt9eKIPWbuZTgsQ1nPkwdrl9PFU=
