language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: lU3Ajj+kJdnxZNBPcCPDaEpwi4VitmgFf3Kk2MGuhYZ7+MDfsWDKT2AVtHfpRm2k5QD+0kNIU/TjdvWL0Gus2E6kGpO1aWbfW82zdByJQaBTj6VR152N/pMaHblfrOWMJnPq0m5/XXMqM8hHPsOO3qkdhpawjWVS+uHR0/xNNDiJRDe1kXvpFtcvI8k0I13FtqpwGj0cMnOqyp6qYXtcX6eY89cx7cJyBsS6GDm5jkRXTUg9I/DG1nS31tpHehqhHBt9hnIGM1Ek3XhuwzbEXJlayl7/xC/or40TSNoCm5bOuavNKh9Zt74wRThD6HDxlxaxzPeoRLbB55zz86mSPx0BsUaHowgkSYe1+jylVVdN9JeD/A76Lk8hH7SsM+wj6Us/+NvB7uedRC8K356cuMmeMC+m5Ztm6TF/48kD5/pQN3SxmtkcBxF02N8h1gHcyCwJ8Z3nUjLrXsihbe7M9ycMoZpyM1qMQuQemGGozcq5qth8ByOlqzWNO4gWTE61i21L+KS//bBs1AuLaaMjLCaMxfyipwLoJ1GEtTsXYs+LaOEJrqPqXCq5reDa9hgOifXQ0JfsYOV0XQHlp9ayNNoPjD6SnZ5GprAAF+M0cb4RKU0IvqU01P3rQRUOWTA7YtLYPJxLDMbD2xxFVMxvbeEQjwid73RutyL56eK3le0=
  app: javahelloapp
