language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: WgnkW7qh+a2s+tF9GRGwpN8bmoy2g/SbqTt21yBHxMznLQQLUJo0ZojaMVVcVglA9Gj/9OYUSge3PMu5TcNnKdKtLj4yjYNMHZhVDU3M6gKE7pOq9EvAH0bVNjt+5ubiBWXncLxp9zOYMJGW8r5I75x9lsQ5Ivt5ElHcHQPtqiIURtujSreBEQoPkFl1CsJTtK6l7rgPG6ZGZAU/GIP9QK19Iz+FZhqmk4aYs1l9AKb1EzWR6wA9xWT5yGhSKaUJ+7Cnyrbo6o2Yb62+nunHq5GUtKYgz3W7p9p8rYMlSUH2rgxGEWHPODd4mG+btVffrP8GfKOMc8unQgIWzIbsU1LrE1mPcrdh6/JfKOiLu6bfg0ctBKvnoDKDSA+3maiChpjpkiXyojX26ZF3gK4oeX9/ItCK/osYnRCl++rwQ5yahUQzb7VuHM+x+GvPTxs7RKsUEPfvs1O6AfYjC/bQTYpePCELJeUMi0a0P8cMbiEvrr9HEU3LltRLUn92XZ37pUbAnxEDLzFLWGEr/g6cVeL7gPrpGjdZdzE4RgEVj4baKte0SZSAeU7YiSeYZl1Mmfds2kRqlSndIedwbqSNiqr2BrB129B1XhTlhajMGwb5YqllX3BQmy/rUlYULKBXMA6dPr6emXw6EeYM/Vu6Y++/WPZ34ATK9OihpJiQThQ=
