language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    - secure: krkBaTqbVJ9j29ERWT0O3f4/NAX4Yg+K5jaUGS5HU7idt7YdMwSzpZe/MOIunkay+NSY7sCsttiEOwcVCGq7RqNLQUS2+7m3qOIhOrzurzZk0WlwrC/AgbGs9AQmHZh8icvTYLVt5TYtaxMZ8Pp+8osbwDmOSwbc1knb+LfSqUZW0L/Ww1plml7pDp/25BklOx0CNgC2TcCgpQKB6bRWUTVFiWNjls7brr4x7iHvRx73k9DftQ3imwUh4yVaxbRD83QBSEpmiZKuMrGf4vOMoI262K1PwKeMA3YKq/3mN6BZGEm+/K8isLM99KQT50217itys/ufKS7/Kopiz01M6bdgUoyqlKXSh9zRDTlQdAC1Kclogi56JecOIVe1lY9RXcDVk6yWXAsnbl0T50zxdFDzykCyKq5SaG2NJo1Cvl7+/Wo6qfJKrhpD507ZE5A1BtEsVKXilvE+C7I8y9xwYqra7xnkne+/O3DwQ0FXtESf4ydah8MqM8PwgEr8SbOhjqO9Y+1KSyTk1BqzsmwfTQNHmdpd3WWrhc5IEso2gCNjgvB8JoBHj2xnR0yqBE4Nq/ULiXJ1Ftd5AJ9BaYnWhUo6bJELF1fCjiFvDlNxN233LdF9+YSOyuQlB3S/rFRBFQezNEBxdg7TYKExqIOB/hO7FTFjvriJ8+4WullZcAg=
